<?php
require_once(dirname(__FILE__) . "/app-config.php");

const APP_LOCALIZATION_CONFIG = array(
	array('id' => APP_ROY_EDITOR, 'url' => '../roy-editor/assets/i18n'),
	array('id' => APP_ROY_EDITOR_BACKEND, 'url' => '../roy-editor/api/i18n'),
	array('id' => APP_ROY_EDITOR_ROY_50_50_SPEED_QUIZ_GAME, 'url' => '../roy-editor/uploads/quiz-game/base/i18n'),
	array('id' => APP_BEE, 'url' => '../roy-bee/assets/i18n'),
	array('id' => APP_BEE_BACKEND, 'url' => '../roy-bee/api/i18n'),
	array('id' => APP_BEE_STAGE, 'url' => '../roy-bee-stage/assets/i18n'),
	array('id' => APP_BEE_STAGE_BACKEND, 'url' => '../roy-bee-stage/api/i18n'),
	array('id' => APP_ROY_50_50_SPEED_QUIZ, 'url' => '../roy-speed-quiz/assets/i18n'),
	array('id' => APP_ROY_50_50_SPEED_QUIZ_GAME, 'url' => '../roy-speed-quiz/uploads/quiz-game/base/i18n'),
);

const APP_LOCALIZATION_CONFIG_DEV = array(
	array('id' => APP_ROY_EDITOR, 'url' => '../../ROY-Editor/src/assets/i18n'),
	array('id' => APP_ROY_EDITOR_BACKEND, 'url' => '../../ROY-Editor/backend/api/i18n'),
	array('id' => APP_ROY_EDITOR_ROY_50_50_SPEED_QUIZ_GAME, 'url' => '../../ROY-Editor/backend/uploads/quiz-game/base/i18n'),
	array('id' => APP_BEE, 'url' => '../../ROY-Bee/src/assets/i18n'),
	array('id' => APP_BEE_BACKEND, 'url' => '../../ROY-Bee/backend/api/i18n'),
	array('id' => APP_BEE_STAGE, 'url' => '../../ROY-Bee/src/assets/i18n'),
	array('id' => APP_BEE_STAGE_BACKEND, 'url' => '../../ROY-Bee/backend/api/i18n'),
	array('id' => APP_ROY_50_50_SPEED_QUIZ, 'url' => '../../ROY-Speed-Quiz/src/assets/i18n'),
	array('id' => APP_ROY_50_50_SPEED_QUIZ_GAME, 'url' => '../../ROY-Speed-Quiz/backend/uploads/quiz-game/base/i18n'),
);

const APP_LOCALES = array(
	'en-main',
	'en-GB',
	'de-DE',
	'en-GB',
	'de-DE',
	// 'en-PS',
	// 'en-BA',
	'hr-HR',
	'cs-CZ',
	'da-DK',
	'nl-NL',
	// 'en-NZ',
	// 'en-RS',
	// 'en-AU',
	// 'en-IL',
	// 'en-IE',
	// 'en-EG',
	// 'en-CY',
	// 'en-SG',
	// 'en-MT',
	'fi-FI',
	'fr-FR',
	// 'fr-MA',
	// 'fr-TN',
	// 'fr-GF',
	// 'fr-MQ',
	// 'fr-GP',
	// 'fr-BE',
	'nl-BE',
	'de-AT',
	'de-LU',
	'fr-LU',
	'de-CH',
	'fr-CH',
	'it-CH',
	'el-GR',
	'hu-HU',
	'it-IT',
	// 'en-NO',
	'pl-PL',
	'pt-PT',
	'ro-RO',
	//'en-RO',
	'sk-SK',
	'sl-SI',
	'es-ES',
	'es-MX',
	'es-CO',
	'es-PE',
	'sv-SE',
	// 'en-SE',
	'tr-TR'
);